spring:
  datasource:
    username: root
    password: aabcd
    url: jdbc:mysql://localhost:3306/CSYE6225?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: update