name: Packer Build

on:
  pull_request:
    types:
      - closed
jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository-
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      # Checkout Repo
      - name: Checkout
        uses: actions/checkout@v2

      # Setup AWS Credential
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Build AMI
      - name: Run packer
        run: packer build -var aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }} -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} AMI.json

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Get Latest AMI ID
      - name: Get AMI ID
        run: |
          latest_ami_id=$(aws ec2 describe-images --owners 807109680293 --query 'Images[].[ImageId, CreationDate]' --output text | sort -k2 -r | head -n1 | awk '{print $1}')
          echo "Latest AMI ID: $latest_ami_id"
          echo "LATEST_AMI_ID=$latest_ami_id" >> $GITHUB_ENV

      # Create or update a Launch Template for the autoscaling group.
      - name: Create or Update Launch Template
        run: |
          TEMPLATE_NAME="example_launch_template"
          TEMPLATE_EXISTS=$(aws ec2 describe-launch-templates --filters "Name=launch-template-name,Values=$TEMPLATE_NAME" --query 'LaunchTemplates[0].LaunchTemplateName' --output text)

          if [ "$TEMPLATE_EXISTS" == "$TEMPLATE_NAME" ]; then
            echo "Updating existing launch template..."
            RESPONSE=$(aws ec2 create-launch-template-version --launch-template-name $TEMPLATE_NAME --launch-template-data "{\"ImageId\":\"$LATEST_AMI_ID\",\"InstanceType\":\"t2.micro\"}")
          else
            echo "Creating new launch template..."
            RESPONSE=$(aws ec2 create-launch-template --launch-template-name $TEMPLATE_NAME --launch-template-data "{\"ImageId\":\"$LATEST_AMI_ID\",\"InstanceType\":\"t2.micro\"}")
          fi

          echo "Launch template response: $RESPONSE"
          TEMPLATE_VERSION=$(echo $RESPONSE | jq '.LaunchTemplate.LatestVersionNumber // .LaunchTemplateVersion.VersionNumber')
          echo "TEMPLATE_VERSION=$TEMPLATE_VERSION" >> $GITHUB_ENV


      # Get the Auto Scaling Group Name
      - name: Get Auto Scaling Group Name
        run: |
          ASG_NAME=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[0].AutoScalingGroupName" --output text)
          echo "ASG_NAME=$ASG_NAME" >> $GITHUB_ENV

      # Update the autoscaling group to use the new Launch Template.
      - name: Update Auto Scaling Group
        run: |
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --launch-template "{\"LaunchTemplateName\":\"example_launch_template\",\"Version\":\"$TEMPLATE_VERSION\"}"

