name: Packer Build

on:
  pull_request:
    types:
      - closed
      - -
jobs:
  # Use the Packer Builder Type
  build-ami:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout Repo
      - name: Checkout
        uses: actions/checkout@v2

      # Setup AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Run Packer Build
      - name: Run packer
        run: packer build ../../AMI.json