name: Java CI with Maven

on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET }}
    steps:
      - name: Checkout Repository-
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run packer
        run: |
          packer validate AMI.json
          packer build AMI.json
          packer build -var aws_access_key=${{ secrets.KEY }} -var aws_secret_key=${{ secrets.SECRET }} AMI.json


